### ISSUE TITLE
Possibility to have two Panels at the same time

### ISSUE THREAD

**Issue by vincentborcard** [Rellac-Rellac/unity-ui-manager#2]
Hi,

Do you think it will possible to have two Panels at the same time on the same Manager?
So to have the ability to Add and Remove Panels in addition to the SetPanel method?

Thank you for the package!
Vincent

**Comment by Rellac-Rellac** [comment]
Hey, sorry for the delay. If you look in the examples you should see how multiple panels can be utilised. I'm open to suggestions for a better implementation if you can let me know why this isn't sufficient
